Repository IRTSA-SoftwareProject/IRTSA-App, pull requests merged in 2018-10, with the labels that each got.

#59 added functionality to edit scan name and description
  .idea/caches/build_file_checksums.ser
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryEditDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanInterface.java
  app/src/main/res/layout/dialog_gallery_edit.xml
  app/src/main/res/layout/fragment_gallery_detail.xml
  app/src/main/res/menu/gallery_detail_toolbar.xml
Labels: feature

#60 add connectivity indicator
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
Labels: feature

#62 add strings.xml file and fix the layout for the gallery detail fragment
  .idea/caches/build_file_checksums.ser
  app/build.gradle
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/res/layout/dialog_save.xml
  app/src/main/res/layout/fragment_gallery_detail.xml
  app/src/main/res/layout/fragment_start_scan.xml
  app/src/main/res/menu/gallery_detail_toolbar.xml
  app/src/main/res/menu/gallery_toolbar.xml
  app/src/main/res/menu/start_scan_toolbar.xml
  app/src/main/res/menu/view_scan_toolbar.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug, feature

#64 Handle orientation change
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/GalleryContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/ScanContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
Labels: bug, enhancement

#65 Add share button
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryEditDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/res/xml/filepaths.xml
Labels: feature

#63 Get scan from server
  .idea/caches/build_file_checksums.ser
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ScanProgressFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/server/Server.java
  app/src/main/res/layout/fragment_gallery_detail.xml
  app/src/main/res/layout/fragment_scan_progress.xml
  app/src/main/res/menu/gallery_toolbar.xml
Labels: feature

#69 Generate documentation
  .travis.yml
  app/build.gradle
  app/docs.gradle
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ScanProgressFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
  gradlew
Labels: feature

#72 Handle extra parameters
  app/src/androidTest/java/com/swinburne/irtsa/irtsa/TestGalleryFragment.java
  app/src/androidTest/java/com/swinburne/irtsa/irtsa/TestStartScanFragment.java
  app/src/androidTest/java/com/swinburne/irtsa/irtsa/TestViewScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ScanProgressFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/res/layout-land/fragment_start_scan.xml
  app/src/main/res/layout-w600dp-h600dp/fragment_start_scan.xml
  app/src/main/res/layout/fragment_start_scan.xml
Labels: feature

#66 scan can now be saved to local storage from GalleryDetailFragment
  .idea/caches/build_file_checksums.ser
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDeleteDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GallerySaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/res/layout/dialog_gallery_save.xml
  app/src/main/res/menu/gallery_detail_toolbar.xml
Labels: feature

#73 altered imageview width to match_parent
  app/src/main/res/layout/gallery_item.xml
Labels: feature

#74 observers of the server now properly unsubscribe on app recreation
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ScanProgressFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
Labels: enhancement

#76 sqlite db connections now close after executing sql
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
Labels: bug

#75 stopped start scan button from being enabled despite invalid input
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
Labels: bug

#77 Add missing comments
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/GalleryContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/ScanContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDeleteDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryEditDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GallerySaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/Scan.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanInterface.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ScanProgressFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/utility/ZoomableImageView.java
Labels: feature

#78 start scan form now properly preserved when app goes out of focus
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
Labels: bug

#79 Mobile gallery detail landscape view
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/res/layout-land/fragment_gallery_detail.xml
  app/src/main/res/layout/fragment_gallery_detail.xml
Labels: feature
