Repository IRTSA-SoftwareProject/IRTSA-App, pull requests merged in 2018-09, with the labels that each got.

#28 Comment codebase
  .idea/modules.xml
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/GalleryContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/ScanContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/Scan.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanInterface.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
Labels: documentation

#31 gallery now refreshes whenever gallery tab is selected
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/GalleryContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/ScanContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
Labels: bug

#32 changes were overwritten by the linting merge, these changes have bee…
  .idea/modules.xml
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ViewPagerAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/GalleryContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/containers/ScanContainerFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
Labels: bug

#33 toolbar now updates on fragment change
  .idea/caches/build_file_checksums.ser
  .idea/modules.xml
  app/build.gradle
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/java/com/swinburne/irtsa/irtsa/ToolbarSetter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
  app/src/main/res/menu/toolbar.xml
  app/src/main/res/menu/toolbar_save.xml
  app/src/main/res/menu/toolbar_scan.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: bug

#36 Pass scan when selected in GalleryAdapter
  .idea/caches/build_file_checksums.ser
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/Scan.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/SaveDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/StartScanFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/scan/ViewScanFragment.java
Labels: feature

#48 gallery now updates its gallery items asynchronously
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
Labels: enhancement

#50 fixed gallery item alignment issues
  .idea/misc.xml
  app/src/main/res/layout/gallery_item.xml
Labels: bug

#44 Remove idea files
  .idea/assetWizardSettings.xml
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
Labels: bug

#51 gallery orders scans by created at date
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryAdapter.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryFragment.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/Scan.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanAccessObject.java
  app/src/main/java/com/swinburne/irtsa/irtsa/model/ScanInterface.java
Labels: feature

#35 added the app theme
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_start_scan.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#54 added delete functionality to toolbar
  .idea/caches/build_file_checksums.ser
  app/build.gradle
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDeleteDialog.java
  app/src/main/java/com/swinburne/irtsa/irtsa/gallery/GalleryDetailFragment.java
  app/src/main/res/layout/dialog_gallery_delete.xml
  app/src/main/res/menu/gallery_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: feature

#56 fixed the issues with the theme
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/swinburne/irtsa/irtsa/MainActivity.java
  app/src/main/res/drawable/launch_screen.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feature
